Fat 1
AnnyRomanova/FastApi_test pull request #1
Opened 2024-11-27 18:52 UTC by AnnyRomanova

Привела приложение к виду MVC, поправила тесты

2024-11-28 13:30 UTC, mas-aleksey requested changes

2024-11-28 13:30 UTC, mas-aleksey commented on src/controllers/post_controller.py
> +            raise ValueError("Cannot get post with id 0")
это я у себя в примере специально сделал чтобы показать возможную ошибку, тут можно убрать строчки 27-28 !

2024-11-28 13:30 UTC, mas-aleksey commented on src/controllers/post_controller.py
> +        for post in self.post_db:
кажется что можно сделать оптимальнее если хранить post_db в виде словаря где ключ будет post_id и значение сам пост, тогда будет проще проверять есть ли такой post_id и получать/удалять.. еще кстати в посте можно хранить не объект автора, а только author_id

2024-11-28 20:14 UTC, AnnyRomanova commented
Обновила базу данных и все, что затрагивалось в связи с этим

2024-11-29 13:49 UTC, mas-aleksey commented on tests/api/test_update_post.py
>  client = TestClient(app)
все таки рекомендую сделать клиента через фикстуру и так же желательно асинхронную!

2024-11-29 13:49 UTC, mas-aleksey commented on src/models/database.py
> +}
в целом ок, у меня вопросов нет.. но если хочешь, можно немного усложнить и добавить модель автора, но придется разделить модели которые используют api и сделать отдельные для db

2024-12-04 10:08 UTC, AnnyRomanova commented on src/models/database.py
> +}
Пока не буду это троогать

2024-12-04 10:24 UTC, mas-aleksey approved these changes

2024-12-04 10:44 UTC, merged